### ISSUE TITLE
Adicionar `svelte-typewriter` a lista

### ISSUE THREAD

**Issue by ghost** [svelte-brasil/awesome-svelte#14]
> Um efeito "typewriter" simples e reutilizável para suas aplicações Svelte

- [Repositório](https://github.com/henriquehbr/svelte-typewriter)
- [Pacote NPM](https://npmjs.com/package/svelte-typewriter)
- [Demo](https://svelte.dev/repl/9dfb73bfa9b34aeea4740fa23f5cde8a)

**Obs:** Seria interessante a criação de uma seção "Animações" a lista, devido ao fato de que a biblioteca não se encaixa na categoria de nenhum dos projetos listados atualmente

**Comment by Demysdcl** [comment]
Pode criar a sessão e mandar a PR que vamos aprovar.

**Comment by Demysdcl** [comment]
Add
