### ISSUE TITLE
Exemplos de uso das libs

### ISSUE THREAD

**Issue by edgarberlinck** [svelte-brasil/awesome-svelte#2]
Seria bacana se cada lib cadastrada aqui tivesse algum pequeno exemplo criado aqui no repositório. O que acham?

**Comment by Demysdcl** [comment]
Muito massa

**Comment by paiva-thiago** [comment]
Qual seria a ideia? Criaria em arquivos Markdown mesmo ou faria como um showcase, com a página estruturada e disponível no github.io?

**Comment by paiva-thiago** [comment]
Vou jogar uns exemplos no markdown. Vou jogar um PR de como eu imagino ser interessante.

**Comment by valmisson** [comment]
Seria melhor fazer os exemplos no https://svelte.dev/repl/ e colocar o link no README na seção de exemplos e remove a pasta exemplos. Assim vai ser mais fácil ver os exemplos e o repositório ficara mais organizado.

**Comment by paiva-thiago** [comment]
> 
> 
> Seria melhor fazer os exemplos no https://svelte.dev/repl/ e colocar o link no README na seção de exemplos e remove a pasta exemplos. Assim vai ser mais fácil ver os exemplos e o repositório ficara mais organizado.


Pode ser interessante, @valmisson! Inclusive já até passei pro REPL do svelte os exemplos que montei, olha só: 

  * [Hello World](https://svelte.dev/repl/f103940f981a45808ed58d55d1b72790)
  * [Bind Values](https://svelte.dev/repl/dab8dc4a8d3442168e066df981d1b650)
  * [Carousel - svelte-carousel](https://svelte.dev/repl/64bc4bc4420c43d2b120ecec54c3b2b1)

Mas tenho uma ressalva: e se alguém tiver alguma sugestão de melhoria nos exemplos? Não tem como editar um app salvo no svelte REPL de outro usuário... Ou o cara faz um fork por lá mesmo?

**Comment by valmisson** [comment]
Sim fazer um fork seria a forma mais elegante de editar  o REPL.

**Comment by valmisson** [comment]
Sugiro também usar a seção de exemplos para colocar apenas exemplos de como usar alguma lib ou exemplos que não tem no https://svelte.dev/examples.
