### ISSUE TITLE
Lib de rotas depreciada

### ISSUE THREAD

**Issue by tvmota** [svelte-brasil/awesome-svelte#21]
Se for possivel atualizar o status da lib SVERO que foi depreciada, para mais informações ver o link da issue do SVERO:
[https://github.com/kazzkiq/svero/issues/68](https://github.com/kazzkiq/svero/issues/68)
Vlw

**Comment by Demysdcl** [comment]
Atualização realizada, se tiver alguma coisa interessante para incluir nosso awesome fique a vontade para abrir PR para nós!
